# Data Cleaning and Validation

## Import libraries

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('..\Data\Dopamine_D2_receptor_01_bioactivity_data_raw.csv')

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\HP\AppData\Local\Temp\ipykernel_11068\3957931753.py:1: SyntaxWarning: invalid escape sequence '\D'
  df = pd.read_csv('..\Data\Dopamine_D2_receptor_01_bioactivity_data_raw.csv')

In [3]:
df.head()

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,NaN,NaN,32111,[],CHEMBL671073,Binding affinity to cloned human Dopamine rece...,B,NaN,NaN,BAO_0000190,...,Homo sapiens,D(2) dopamine receptor,9606,NaN,NaN,IC50,nM,UO_0000065,NaN,9800.0
1,NaN,NaN,33282,[],CHEMBL671073,Binding affinity to cloned human Dopamine rece...,B,NaN,NaN,BAO_0000190,...,Homo sapiens,D(2) dopamine receptor,9606,NaN,NaN,IC50,nM,UO_0000065,NaN,50.0
2,NaN,NaN,38258,[],CHEMBL671073,Binding affinity to cloned human Dopamine rece...,B,NaN,NaN,BAO_0000190,...,Homo sapiens,D(2) dopamine receptor,9606,NaN,NaN,IC50,nM,UO_0000065,NaN,25.0
3,NaN,NaN,39387,[],CHEMBL671073,Binding affinity to cloned human Dopamine rece...,B,NaN,NaN,BAO_0000190,...,Homo sapiens,D(2) dopamine receptor,9606,NaN,NaN,IC50,nM,UO_0000065,NaN,360.0
4,NaN,NaN,39391,[],CHEMBL671073,Binding affinity to cloned human Dopamine rece...,B,NaN,NaN,BAO_0000190,...,Homo sapiens,D(2) dopamine receptor,9606,NaN,NaN,IC50,nM,UO_0000065,NaN,300.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2475 entries, 0 to 2474
Data columns (total 46 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   action_type                120 non-null    object
 1   activity_comment           1164 non-null   object
 2   activity_id                2475 non-null   int64
 3   activity_properties        2475 non-null   object
 4   assay_chembl_id            2475 non-null   object
 5   assay_description          2475 non-null   object
 6   assay_type                 2475 non-null   object
 7   assay_variant_accession    0 non-null      float64
 8   assay_variant_mutation     0 non-null      float64
 9   bao_endpoint               2475 non-null   object
 10  bao_format                 2475 non-null   object
 11  bao_label                  2475 non-null   object
 12  canonical_smiles           2437 non-null   object
 13  data_validity_comment      11 non-null     object
 14  data_validity_description  11 non-null     object
 15  document_chembl_id         2475 non-null   object
 16  document_journal           1336 non-null   object
 17  document_year              1600 non-null   float64
 18  ligand_efficiency          637 non-null    object
 19  molecule_chembl_id         2475 non-null   object
 20  molecule_pref_name         978 non-null    object
 21  parent_molecule_chembl_id  2475 non-null   object
 22  pchembl_value              1091 non-null   float64
 23  potential_duplicate        2475 non-null   int64
 24  qudt_units                 1580 non-null   object
 25  record_id                  2475 non-null   int64
 26  relation                   1568 non-null   object
 27  src_id                     2475 non-null   int64
 28  standard_flag              2475 non-null   int64
 29  standard_relation          1568 non-null   object
 30  standard_text_value        812 non-null    object
 31  standard_type              2475 non-null   object
 32  standard_units             1580 non-null   object
 33  standard_upper_value       0 non-null      float64
 34  standard_value             1572 non-null   float64
 35  target_chembl_id           2475 non-null   object
 36  target_organism            2475 non-null   object
 37  target_pref_name           2475 non-null   object
 38  target_tax_id              2475 non-null   int64
 39  text_value                 812 non-null    object
 40  toid                       0 non-null      float64
 41  type                       2475 non-null   object
 42  units                      1355 non-null   object
 43  uo_units                   1580 non-null   object
 44  upper_value                1 non-null      float64
 45  value                      1572 non-null   float64
dtypes: float64(9), int64(6), object(31)
memory usage: 889.6+ KB

In [5]:
df.duplicated().sum()

np.int64(0)

### **Labeling compounds as either being active, inactive or intermediate**
The bioactivity data is in the IC50 unit. Compounds having values of less than 1000 nM will be considered to be **active** while those greater than 10,000 nM will be considered to be **inactive**. As for those values in between 1,000 and 10,000 nM will be referred to as **intermediate**.

In [6]:
df['standard_value'].isna().sum()

np.int64(903)

In [7]:
df.isna().sum()

action_type                  2355
activity_comment             1311
activity_id                     0
activity_properties             0
assay_chembl_id                 0
assay_description               0
assay_type                      0
assay_variant_accession      2475
assay_variant_mutation       2475
bao_endpoint                    0
bao_format                      0
bao_label                       0
canonical_smiles               38
data_validity_comment        2464
data_validity_description    2464
document_chembl_id              0
document_journal             1139
document_year                 875
ligand_efficiency            1838
molecule_chembl_id              0
molecule_pref_name           1497
parent_molecule_chembl_id       0
pchembl_value                1384
potential_duplicate             0
qudt_units                    895
record_id                       0
relation                      907
src_id                          0
standard_flag                   0
standard_relation             907
standard_text_value          1663
standard_type                   0
standard_units                895
standard_upper_value         2475
standard_value                903
target_chembl_id                0
target_organism                 0
target_pref_name                0
target_tax_id                   0
text_value                   1663
toid                         2475
type                            0
units                        1120
uo_units                      895
upper_value                  2474
value                         903
dtype: int64

In [9]:
selection = ['molecule_chembl_id','canonical_smiles','standard_value']
df2 = df[selection]

In [10]:
df2.dropna(inplace=True,axis=0)

C:\Users\HP\AppData\Local\Temp\ipykernel_11068\600528996.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.dropna(inplace=True,axis=0)

In [11]:
df2.shape

(1570, 3)

In [12]:
df['standard_type'].unique()

array(['IC50'], dtype=object)

In [13]:
df['standard_units'].unique()

array(['nM', nan], dtype=object)

In [14]:
df['target_organism'].unique()

array(['Homo sapiens'], dtype=object)

In [15]:
df['target_pref_name'].unique()

array(['D(2) dopamine receptor'], dtype=object)

### the data cleaning process and data validation is done by ensure that only useful column will be insert the training phase with no duplicates in data also make sure only ic50 standard value ,organism homo sapiens and only D2 dopamine are in the data

In [16]:
df2

,molecule_chembl_id,canonical_smiles,standard_value
0,CHEMBL303519,c1cnc(N2CCN(Cc3cccc4c3Cc3ccccc3-4)CC2)nc1,9800.0
1,CHEMBL292943,COc1ccc(-c2cccc(CN3CCN(c4ncccn4)CC3)c2)cc1,50.0
2,CHEMBL61682,Fc1ccc(-c2cncc(CN3CCN(c4ccccc4F)CC3)c2)cc1,25.0
3,CHEMBL64487,COc1ccccc1-c1cccc(CN2CCN(c3ncccn3)CC2)c1,360.0
4,CHEMBL64597,c1cnc(N2CCN(Cc3cccc(-c4ccsc4)c3)CC2)nc1,300.0
...,...,...,...
2470,CHEMBL5924660,COc1ccc(OCCCN2CCN(C(=O)c3ccc(Cl)cc3)CC2)cc1,9000.0
2471,CHEMBL4459353,COc1ccc(OCCN(C)CCN(C)C(=O)c2ccc(OC)cc2)cc1,18000.0
2472,CHEMBL4471482,COc1ccc(N(C)CCN2CCN(C(=O)c3cc4ccccc4[nH]3)CC2)cc1,100000.0
2473,CHEMBL4442293,COc1ccc(OCCCN2CCN(C(=O)c3cc4ccccc4[nH]3)CC2)cc1,691.0
2474,CHEMBL4580359,COc1ccc(OCCCCN2CCN(C(=O)c3cc4ccccc4[nH]3)CC2)cc1,1200.0

In [17]:
df2.isna().sum()

molecule_chembl_id    0
canonical_smiles      0
standard_value        0
dtype: int64

In [18]:
df2.to_csv('..\Data\Dopamine_D2_receptor_02_bioactivity_data_raw.csv', index=False)

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\HP\AppData\Local\Temp\ipykernel_11068\394170536.py:1: SyntaxWarning: invalid escape sequence '\D'
  df2.to_csv('..\Data\Dopamine_D2_receptor_02_bioactivity_data_raw.csv', index=False)