# **Bioinformatics Project - Computational Drug Discovery [Part 1] Download Bioactivity Data**

we will be performing Data Collection and Pre-Processing from the ChEMBL Database.

## **Installing libraries**

Install the ChEMBL web service package so that we can retrieve bioactivity data from the ChEMBL Database.

In [1]:
! pip install chembl_webresource_client

Requirement already satisfied: chembl_webresource_client in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (0.10.9)
Requirement already satisfied: urllib3 in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (from chembl_webresource_client) (2.32.4)
Requirement already satisfied: requests-cache~=1.2 in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (from chembl_webresource_client) (1.3.1)
Requirement already satisfied: easydict in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: attrs>=21.2 in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Requirement already satisfied: cattrs>=22.2 in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Requirement already satisfied: platformdirs>=2.5 in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests-cache~=1.2->chembl_webresource_client) (4.3.7)
Requirement already satisfied: url-normalize>=2.0 in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests-cache~=1.2->chembl_webresource_client) (2.2.1)
Requirement already satisfied: typing-extensions>=4.14.0 in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.18.4->chembl_webresource_client) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests>=2.18.4->chembl_webresource_client) (2025.8.3)

## **Importing libraries**

In [2]:
import pandas as pd
from chembl_webresource_client.new_client import new_client
import matplotlib.pyplot as plt

c:\Users\HP\AppData\Local\Programs\Python\Python313\Lib\site-packages\chembl_webresource_client\__init__.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __version__ = __import__('pkg_resources').get_distribution('chembl_webresource_client').version

## **Search for Target protein**

### **Target search for Dopamine D2 receptor**

In [3]:
target = new_client.target
target_query = target.search('Dopamine D2 receptor')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,D(2) dopamine receptor,32.0,False,CHEMBL217,"[{'accession': 'P14416', 'component_descriptio...",SINGLE PROTEIN,9606.0
1,[],Canis lupus familiaris,D(2) dopamine receptor,32.0,False,CHEMBL2703,"[{'accession': 'Q9GJU1', 'component_descriptio...",SINGLE PROTEIN,9615.0
2,[],Bos taurus,D(2) dopamine receptor,32.0,False,CHEMBL3998,"[{'accession': 'P20288', 'component_descriptio...",SINGLE PROTEIN,9913.0
3,[],Mus musculus,D(2) dopamine receptor,32.0,False,CHEMBL3427,"[{'accession': 'P61168', 'component_descriptio...",SINGLE PROTEIN,10090.0
4,[],Rattus norvegicus,D(2) dopamine receptor,32.0,False,CHEMBL339,"[{'accession': 'P61169', 'component_descriptio...",SINGLE PROTEIN,10116.0
...,...,...,...,...,...,...,...,...,...
2679,[],Homo sapiens,Protein cereblon/Tyrosine-protein kinase Lck,0.0,False,CHEMBL6066027,"[{'accession': 'P06239', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606.0
2680,[],Homo sapiens,Protein cereblon/Tyrosine-protein kinase JAK3,0.0,False,CHEMBL6066057,"[{'accession': 'P52333', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606.0
2681,[],Homo sapiens,Tyrosine-protein kinase BTK/Tyrosine-protein k...,0.0,False,CHEMBL6066563,"[{'accession': 'P06241', 'component_descriptio...",PROTEIN FAMILY,9606.0
2682,[],Homo sapiens,Tyrosine-protein kinase BTK/Tyrosine-protein k...,0.0,False,CHEMBL6066564,"[{'accession': 'P06239', 'component_descriptio...",PROTEIN FAMILY,9606.0
2683,[],Homo sapiens,Tyrosine-protein kinase BTK/Tyrosine-protein k...,0.0,False,CHEMBL6066565,"[{'accession': 'P07948', 'component_descriptio...",PROTEIN FAMILY,9606.0

### Dataset Overview: Dopamine D2 receptor Target Classifications

In this dataset, the molecular bioactivity is categorized by the specific biological structure being targeted. Understanding these classifications is useful for determining how we handle the data for machine learning models:

* **Single Protein:** The bioactivity is measured against the standalone Dopamine D2 receptor protein or an individual related receptor (like ErbB-2 or ErbB-3). 
* **Protein-Protein Interaction:** The target is the physical interface between Dopamine D2 receptor and another distinct protein (e.g., CCN2). Compounds here are typically designed to disrupt or enhance this binding.
* **Protein Family:** The target encompasses a broader group of related receptors simultaneously, such as drugs that affect both HER1 (Dopamine D2 receptor) and HER2.
* **Protein Complex:** The target is a functional, multi-protein unit consisting of bound subunits, such as the ErbB-2/ErbB-3 heterodimer.
* **Chimeric Protein:** An engineered, hybrid protein combining domains from different sources (e.g., an MER/Dopamine D2 receptor chimera), typically used in specialized laboratory assays.

### **Select and retrieve bioactivity data for *Dopamine D2 receptor***

### we will select the first entity as it it has the perfect match
* Target type --> Single (the Dopamine D2 receptor test alone)
* organism --> Mus musculus (the test applied on humans)

In [4]:
selected_target = targets.target_chembl_id[0]
selected_target

'CHEMBL217'

Here, we will retrieve only bioactivity data for *Dopamine D2 receptor* (CHEMBL217) that are reported as pChEMBL values.

In [5]:
activity = new_client.activity
data = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

### we use standard type IC50 which is the standard metric used to measure a drug's potency. Specifically, it tells you exactly how much of a chemical compound is needed to inhibit a biological target (like the Dopamine D2 receptor protein) by 50%

### In a machine learning pipeline predicting molecular bioactivity for targets like the Dopamine D2 receptor protein, the IC50 value is typically your main target variable (the y value your model is trying to predict)

<center>
  <img src="https://journals.plos.org/plosone/article/figure/image?id=10.1371/journal.pone.0106186.g002&size=large" width="1200" height="600">
</center>

In [6]:
df = pd.DataFrame.from_dict(data)

In [7]:
df

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,32111,[],CHEMBL671073,Binding affinity to cloned human Dopamine rece...,B,None,None,BAO_0000190,...,Homo sapiens,D(2) dopamine receptor,9606,None,None,IC50,nM,UO_0000065,None,9800.0
1,None,None,33282,[],CHEMBL671073,Binding affinity to cloned human Dopamine rece...,B,None,None,BAO_0000190,...,Homo sapiens,D(2) dopamine receptor,9606,None,None,IC50,nM,UO_0000065,None,50.0
2,None,None,38258,[],CHEMBL671073,Binding affinity to cloned human Dopamine rece...,B,None,None,BAO_0000190,...,Homo sapiens,D(2) dopamine receptor,9606,None,None,IC50,nM,UO_0000065,None,25.0
3,None,None,39387,[],CHEMBL671073,Binding affinity to cloned human Dopamine rece...,B,None,None,BAO_0000190,...,Homo sapiens,D(2) dopamine receptor,9606,None,None,IC50,nM,UO_0000065,None,360.0
4,None,None,39391,[],CHEMBL671073,Binding affinity to cloned human Dopamine rece...,B,None,None,BAO_0000190,...,Homo sapiens,D(2) dopamine receptor,9606,None,None,IC50,nM,UO_0000065,None,300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2470,None,1272424,28986668,[],CHEMBL5739214,D2 DAR Beta-Arrestin Recruitment Assay: For a ...,B,None,None,BAO_0000190,...,Homo sapiens,D(2) dopamine receptor,9606,None,None,IC50,nM,UO_0000065,None,9000.0
2471,None,1272426,28986674,[],CHEMBL5739214,D2 DAR Beta-Arrestin Recruitment Assay: For a ...,B,None,None,BAO_0000190,...,Homo sapiens,D(2) dopamine receptor,9606,None,None,IC50,nM,UO_0000065,None,18000.0
2472,None,1272428,28986680,[],CHEMBL5739214,D2 DAR Beta-Arrestin Recruitment Assay: For a ...,B,None,None,BAO_0000190,...,Homo sapiens,D(2) dopamine receptor,9606,None,None,IC50,nM,UO_0000065,None,100000.0
2473,None,1272433,28986695,[],CHEMBL5739214,D2 DAR Beta-Arrestin Recruitment Assay: For a ...,B,None,None,BAO_0000190,...,Homo sapiens,D(2) dopamine receptor,9606,None,None,IC50,nM,UO_0000065,None,691.0
2474,None,1272434,28986698,[],CHEMBL5739214,D2 DAR Beta-Arrestin Recruitment Assay: For a ...,B,None,None,BAO_0000190,...,Homo sapiens,D(2) dopamine receptor,9606,None,None,IC50,nM,UO_0000065,None,1200.0

In [8]:
df.to_csv('Dopamine_D2_receptor_01_bioactivity_data_raw.csv', index=False)